apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: hello-world
  name: hello
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: docker.io/kontena/hello-world:latest
        imagePullPolicy: Always
        name: hello
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 9292
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 9292
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: RACK_ENV
          value: production
        ports:
        - containerPort: 9292
          name: hello
